### ISSUE TITLE
Enviar notificação quando uma nota for atualizada

### ISSUE THREAD

**Issue by carloshgr** [lucis/ufcg-pro#10]

**Comment by luciannojunior** [comment]
Opa, @carloshgr. Por mais que essa feature seja muito legal, ela é meio inviável de ser implementada na extensão pela sua arquitetura. Todas as features que fazemos ocorrem a nível de "apresentação", sem necessidade de haver um servidor da extensão propriamente.

Talvez isso seja alcançável atráves do uso de [`serviceWorkers`](https://developers.google.com/web/fundamentals/primers/service-workers?hl=pt-BR) colocando trabalhos em background, mas não sei dizer ao certo se é possível mesmo.

**Comment by carloshgr** [comment]
E aí @luciannojunior , tudo certo? 

Eu também não conheço os detalhes de uma possível implementação dessa feature.
Decidi abrir a issue, pois, me interessei bastante pela sua ideia - apesar de não saber nada de Javascript. Com certeza vai ser uma das próximas coisas que eu irei estudar. Abraço :)

**Comment by ramonfragoso** [comment]
Opa pessoal, existe uma ferramenta chamada EmailJS, que torna possível enviar emails através de uma simples requisição, porém a versão gratuita dessa ferramenta permite enviar apenas 200 emails por mês. Acredito que isso pode ser usado enquanto um servidor de envio de email é desenvolvido em paralelo.

**Comment by luciannojunior** [comment]
@ramonfragoso essa parte de realmente enviar o e-mail seria tranquila de resolver, o [SendGrid](https://sendgrid.com/pricing/), por exemplo, tem uma quota bem razoável no plano gratuito (100 emails por dia), mas o gargalo é o processamento das páginas do controle pra realmente analisar se as notas mudaram. 

Quem quiser, poderia fazer um script servidor (com Node.js ou Python por exemplo) que um aluno poderia subir na sua própria máquina e ficar fazendo essa análise. @carloshgr e @ramonfragoso, caso queiram se inspirar, fiz uns script há uns anos que faziam mais ou menos isso: https://github.com/luciannojunior/gustavovaipagarlinear/blob/master/server.js
