### ISSUE TITLE
Lidar com upload de csvs sem notas quando prof está preenchendo

### ISSUE THREAD

**Issue by nazareno** [lucis/ufcg-pro#13]
Me enganei e meu cabeçalho tinha 'Nota 1', 'Nota 2' em lugar de 'nota1', 'nota2'. A interface não dá feedback sobre quantas notas foram encontradas no csv, então demorei muito a entender que não estava sendo encontrado nada e por isso não estava sendo preenchido nada. Também não há como fazer upload de um segundo arquivo pra corrigir o 1o sem recarregar a página.

**Comment by lucis** [comment]
@nazareno Acredito que o PR [#12](https://github.com/lucis/ufcg-pro/pull/12) resolve esse problema.

Caso não, por favor reabrir a _issue_ e me passar um CSV de exemplo.

Obrigado :)
