### ISSUE TITLE
Page Not Found ao tentar exportar horário.

### ISSUE THREAD

**Issue by henriqueln7** [lucis/ufcg-pro#14]
Ao tentar exportar o meu horário a partir das abas Turmas em Curso, fui redirecionado para a página https://gist.github.com/luciannojunior/1243ac0bd195647141c7d7f5d3f2691a, que retorna um erro 404.

**Comment by lucis** [comment]
_On it!_

Obrigado, @henriqueln7

**Comment by lucasmedeiros** [comment]
Olá @lucis, vi que a PR que resolve essa issue foi merjada. A versão atualizada já foi para a loja de extensões do Chrome? Se sim, como faz para atualizar? Tentei exportar os horários agora e não funcionou

PS: A matrícula com 1 clique funcionou direitinho, mto obrigado por essa extensão ❤️

**Comment by lucis** [comment]
Opa, @lucasmedeiros. 

Não não, ainda não lancei. Tentarei fazer isso hoje!

**Comment by lucis** [comment]
@lucasmedeiros talvez demore para atualizar no Chrome (tenho lido reports que tem piorado o tempo de review de extensões), mas já subi a **[v1.1.0](https://github.com/lucis/ufcg-pro/releases/tag/1.1.0)**.

![image](https://user-images.githubusercontent.com/18706156/75936965-6014c000-5e62-11ea-8a10-9a5693ff63ab.png) 

No Firefox, como a distribuição é minha, é só esperar no máximo 24hrs para atualizar.
