### ISSUE TITLE
Injeção de CSS forçada

### ISSUE THREAD

**Issue by JuanBarros2** [lucis/ufcg-pro#19]
Olá, tudo bem? 
Estava com a extensão ligada enquanto desenvolvia um site.
O site estava tendo um comportamento estranho, pois uma imagem 
estava com problema para aparecer em tela. Fui inspecionar o elemento e acabei achando 
isso: 
![image](https://user-images.githubusercontent.com/11728655/76707909-bb03ae00-66d1-11ea-91ef-ee7eeb56fe5d.png)
Acredito que o css da extensão está tendo efeito colateral em outras páginas que não sejam a do
controle.

**Comment by davigsousa** [comment]
Passei por isso também, e se eu não me engano, é porque além das páginas do controle, ela também é ativada no localhost.

**Comment by lucis** [comment]
Consertado em #20 . Vou lançar ASAP
