### ISSUE TITLE
"Ocorrendo agora" avisou aula antes da hora

### ISSUE THREAD

**Issue by lucis** [lucis/ufcg-pro#6]
Caso ocorreu para um professor, mas não consegui replicar. Eram 13:00 mais ou menos e a próxima aula era de 14:00, mas a UI avisou que tal aula já estaria acontecendo.

Pode ser alguma coisa louca do horário em Javascript

**Comment by issilva5** [comment]
![image](https://user-images.githubusercontent.com/39525169/69633222-8b4f6e00-102e-11ea-8dc3-cacbef822656.png)

O problema também acontece comigo, aparentemente o problema é do Javascript que está considerando como se houvesse horário de verão.

Instanciando um objeto Date no console do browser, como é feio no getAulaProxima do Home.vue, ele pega a data considerando horário de verão.

**Comment by luciannojunior** [comment]
*Solução:* esperar o pseudo horário de verão acabar.

Ah, entendi. Esse problema ocorreu em alguns cantos mesmo... Acho que na hora de pegar a gente teria que cravar o GMT de Recife?? É estranho porque na minha máquina eu não fiz nenhuma mudança mas o horário tá ok. @issilva5 no caso, o horário da tua máquina tava okay mas o `new Date()` pegou uma hora adiantado né?

**Comment by issilva5** [comment]
Sim, o horário estava certo, mas o new Date() pegava o horário de verão.

**Comment by luciannojunior** [comment]
@issilva5 seria possível tu fazer uns testes pra mim de como poderíamos fazer isso (de preferência sem colocar bibliotecas externas), porque não consigo reproduzir esse problema do horário de verão na minha máquina. Talvez ver algo como [isso](https://stackoverflow.com/questions/11887934/how-to-check-if-the-dst-daylight-saving-time-is-in-effect-and-if-it-is-whats)

Tipo, não é "não considerar o horário de verão", porque o problema é achar que está no horário de verão quando o país extinguiu... Aí não sei bem como resolver esse problema sem fazer uma verificação hardcoded.

**Comment by issilva5** [comment]
`hoje = new Date(new Date().toLocaleString("en-US", {timeZone: "America/Recife"}))`

No console do browser da minha máquina consegui fazer ele pegar o horário certo, dessa forma

**Comment by luciannojunior** [comment]
@issilva5 qual o a representação em String de um `new Date()` no seu console javascript? No final ele diz em qual timezone está configurado.

Por mais que esta solução conserte este problema, não acho que seria legal marretar um timezone específico (ex: caso o usuário esteja em uma viagem no exterior e esteja preocupado em saber qual aula está perdendo). 

Ainda não consegui entender o que ocasiona este problema.

**Comment by issilva5** [comment]
Fri Dec 06 2019 12:41:12 GMT-0200 (Brasilia Summer Time)

**Comment by luciannojunior** [comment]
@issilva5 Achei o problema, e é no Chrome/Chromium, você pode ver a issue [aqui](https://bugs.chromium.org/p/chromium/issues/detail?id=1009000&can=1&q=timezone&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). Aparentemente, o **Chrome 78** já está com o problema corrigido.

Confirma pra mim que é isso, aí eu fecho a issue, por favor :)
